<?php
/**
 * Copyright © Mageside. All rights reserved.
 * See MS-LICENSE.txt for license details.
 */

/** @var Mageside\MultipleCustomForms\Block\Widget\CustomForm\Fields\Type\FileType $block */

$field = $block->getField();
?>
<!-- <div class="field input file <?= /* @noEscape */ $field->getRequired() ? 'required' : ''; ?>">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldHtmlId()); ?>">
        <span><?= $block->escapeHtml($field->getTitle()); ?></span>
    </label>
    <div class="control validation-block">
        <div class="upload-wrapper-<?= $block->escapeHtmlAttr($field->getId()); ?>"
             data-bind="scope: 'uploader-<?= $block->escapeHtmlAttr($field->getId()); ?>'">
            <!-- ko template: getTemplate() --><!-- /ko -->
   <!--      </div>
    </div>
    <?php if ($block->getComment()) : ?>
        <p class="note"><span><?= $block->escapeHtml($block->getComment()); ?></span></p>
    <?php endif; ?>
</div> 
 -->
