<?php
declare(strict_types=1);

?>
<div class="review-gallery-widget">
    <div class="widget-header">
        <span class="title">Photos</span>
        <span class="close-button"></span>
    </div>
    <div class="widget-content">
        <div class="review-gallery-photos">
            <div class="review-gallery-wrapper" id="review-gallery-widget">
                <div class="swiper-wrapper"></div>
                <div class="swiper-button-next nav-button"></div>
                <div class="swiper-button-prev nav-button"></div>
            </div>
        </div>
        <div class="review-gallery-content">

        </div>
    </div>
</div>
