<?php
/**
 * @var $block MageCloud\DeferJs\Block\Adminhtml\System\Form\Field\Button
 * @var $jsonHelper \Magento\Framework\Json\Helper\Data
 */
$jsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');
?>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm',
        'Magento_Ui/js/modal/alert'
    ], function ($, confirm, alert) {
        window.siteSpeedTest = function(){
            confirm({
                content: 'This operation can take a some time. Continue?',
                actions: {
                    confirm: function () {
                        $.ajax({
                            url: '<?php echo $block->getGTMetrixSpeedTestUrl() ?>',
                            type: "post",
                            dataType: "html",
                            data: {
                                form_key: FORM_KEY,
                                api_endpoint: $('#defer_js_speed_test_gtmetrix_api_endpoint').val(),
                                api_username: $('#defer_js_speed_test_gtmetrix_api_username').val(),
                                api_key: $('#defer_js_speed_test_gtmetrix_api_key').val()
                            },
                            showLoader: true
                        }).done(function(data) {
                            alert({
                                title: 'Speed Test Results:',
                                content: data
                            });
                        });
                    }
                }
            });
        };

        window.openModal = function (url, label) {
            window.open(url, label, getPopupParams());
        };

        function getPopupParams (w, h, l, t) {
            this.screenX = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
            this.screenY = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
            this.outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
            this.outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
            this.width = w ? w : 500;
            this.height = h ? h : 420;
            this.left = l ? l : parseInt(this.screenX + ((this.outerWidth - this.width) / 2), 10);
            this.top = t ? t : parseInt(this.screenY + ((this.outerHeight - this.height) / 2.5), 10);

            return (
                'width=' + this.width +
                ',height=' + this.height +
                ',left=' + this.left +
                ',top=' + this.top
            );
        }
    });
</script>
<?php echo $block->getButtonHtml() ?>
