<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_ChatGPT
 * @author     Extension Team
 * @copyright  Copyright (c) 2024 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/* @var \Bss\ChatGPT\Block\ChatGPT\ChatGPT $block */
?>

<p id="chatgpt-alert"></p>

<div class="modal modal-chat_gpt chatgptmodal" style="display: none;">
    <div class="modal-body">
        <div class="modal-content modal-content-chatgpt">
            <div class="field field-name-metatitle required">
                <label class="label label-title-chatgpt" for="prompt">
                    <span><?= /* @noEscape */ __('Enter Custom Prompt') ?></span>
                </label>
                    <p class="note">
                        <?= /* @noEscape */ __("(*) Select the product attributes in the attribute
                        box below to give ChatGPT some input to generate content.
                        The selected attributes will be put in curly brackets {{ }} and
                        separated by a semicolon ; in the prompt box.") ?>
                    </p>
                <div class="control chatgpt-control">
                    <div class="model-left">
                        <label class="label-chatgpt" for="chatgpt-attributes">
                            <?= /* @noEscape */ __('Attributes') ?>
                        </label>

                        <select id="chatgpt-attributes" class="chatgpt-variables" multiple>
                            <?php foreach ($block->getAllAttributesWithoutProduct() as $code => $value): ?>
                                <option
                                    value="<?= /* @noEscape */ $code ?>"
                                    data-value="<?= /* @noEscape */ $value ?>"
                                    data-title="<?= /* @noEscape */ $value ?>">
                                    <?= /* @noEscape */ $value ?>
                                </option>
                            <?php endforeach; ?>
                        </select>

                        <div class="chatgpt-checkbox">
                            <input id="all-attr" type="checkbox" title="Use all attributes" >
                            <label for="all-attr"><?= /* @noEscape */ __('Use all attributes') ?></label>
                        </div>
                    </div>
                    <div class="model-right">
                        <div>
                            <label class="label-chatgpt" for="role">
                                <?= /* @noEscape */ __('System role') ?>
                            </label>
                            <div class="input-wrapper">
                                <input type="text" id="system_role" name="role-chatgpt" title="Role ChatGPT">
                                <span class="reload-icon">&#8635;</span>
                            </div>
                        </div>
                        <br>
                        <div>
                            <label class="label-chatgpt" for="prompt">
                                <?= /* @noEscape */ __('Prompt') ?>
                            </label>
                            <textarea rows="11" id="prompt" name="prompt-chatgpt" title="Prompt ChatGPT"></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
    "#chatgpt-alert": {
    "Bss_ChatGPT/js/form-attributes":{
        "url": "<?= /* @noEscape */ $block->getUrlMassAction() ?>",
        "form_key": "<?= /* @noEscape */ $block->getFormKey() ?>",
        "message_default": <?= /* @noEscape */ $block->getAllMessDefault() ?>
    }
}

}
</script>
