<?php
declare(strict_types=1);

/** @var $block \Mirasvit\Review\Block\Product\Review\Uploader */

?>
<?php if($block->displayReviewPhoto()):?>
    <div class="field review-field-photos admin__field ">
        <p class="label admin__field-label">
            <span><?= $block->escapeHtml(__('Photos')); ?></span>
        </p>
        <input type="hidden" name="photos">
        <div class="upload-wrapper admin__field-control control" data-bind="scope: 'uploader'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>

    <script type="text/x-magento-init">
    {
        ".upload-wrapper": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "uploader": {
                        "component":"Mirasvit_Review/js/image-uploader",
                        "template": "ui/form/element/uploader/uploader",
                        "isMultipleFiles": "true",
                        "previewTmpl":"Mirasvit_Review/form/preview",
                        "dataScope" : "photo[]",
                        "resizeConfig": <?= \Mirasvit\Core\Service\SerializeService::encode($block->getResizeConfig()) ?>,
                        "uploaderConfig": {
                            "url": "<?= $block->escapeUrl($block->getUrl('mst_review/review/upload')); ?>",
                            "maxNumFiles":  "<?= $block->escapeHtml($block->getMaxNumFiles()); ?>"
                        }
                    }
                }
            }
        }
    }

    </script>
<?php endif;?>
