<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Aheadworks\Helpdesk\Block\Contact\Form $block */
?>
<?php if ($block->getDepartments()) :?>
    <div class="field department_id required text-left inline-block mag-wpx" style="display:none; opacity: 0;">
        <label for="department_id" class="label"><span><?php echo $block->escapeHtml(__('Department')); ?></span></label>
        <div class="control">
            <select id="department_id" name="department_id">
                <?php foreach ($block->getDepartments() as $departmentId => $name): ?>
                    <option value="<?php echo $block->escapeHtml($departmentId); ?>">
                        <?php echo $block->escapeHtml($name); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <script type="text/x-magento-init">
            {
                ".contact .telephone": {
                    "awHelpdeskContactForm": {"awHelpdeskSelector":".contact .department_id"}
                }
            }
        </script>
    </div>
<?php endif; ?>
<div class="aw-helpdesk-file-upload__container">
    <ul id="aw-helpdesk-attachments-added" style="display: none;"></ul>
    <script id="aw-helpdesk-attachments-added-template" type="text/x-magento-template">
        <li>
            <span><%- fileName %> (<%- fileSize %>)</span><a href="#" class="action-item-remove"/>
            <input type="hidden" name="attachment[<%- index %>][name]" value="<%- fileName %>" />
            <input type="hidden" name="attachment[<%- index %>][file]" value="<%- file %>" />
            <input type="hidden" name="attachment[<%- index %>][removed]" data-role="remove" value="0" />
        </li>
    </script>
    <span class="aw-helpdesk-file-upload">
        <span id="aw-helpdesk-attachments-add-link" class="aw-helpdesk-file-upload__link" data-switch-title="<?php echo $block->escapeHtml(__('Add another file')) ?>"><?php echo $block->escapeHtml(__('Add file')) ?></span>
        <input type="file" id="aw-helpdesk-attachments" name="file[]" data-url="/aw_helpdesk/ticket/upload/" multiple />
    </span>
    <div id="aw-helpdesk-attachments-error" style="display: none;"></div>
    <script type="text/x-magento-init">
        {
            "#aw-helpdesk-attachments": {
                "awHelpdeskFileUpload": {
                    "addLink": "#aw-helpdesk-attachments-add-link",
                    "itemTemplate": "#aw-helpdesk-attachments-added-template",
                    "itemsContainer": "#aw-helpdesk-attachments-added",
                    "removeLinks": ".action-item-remove",
                    "errorContainer": "#aw-helpdesk-attachments-error"
                }
            }
        }
    </script>
</div>