<?php
/** @var \Mirasvit\SeoSitemap\Block\Map $block */

$categoryBlock = $block->getChildBlock('map.category');
$storeBlock    = $block->getChildBlock('map.store');
$cmsPageBlock  = $block->getChildBlock('map.cms_page');
?>
<?= $block->getChildHtml('map.pager') ?>
    <div class="seositemap-map">
        <table>
            <tr>
                <td width="50%">
                    <h3><?= $categoryBlock->getTitle() ?></h3>
                    <ul>
                        <?php foreach ($categoryBlock->getCollection() as $item): ?>
                            <li class="level-<?= $item->getLevel() ?>">
                                <a href="<?= $item->getUrl() ?>">
                                    <?= $item->getName() ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </td>

                <td width="50%">
                    <?php if ($block->isFirstPage()): ?>
                        <?php if ($storeBlock->canShowStores()): ?>
                            <h3><?= $storeBlock->getTitle() ?></h3>
                            <ul class="stores">
                                <?php foreach ($storeBlock->getStores() as $store): ?>
                                    <li>
                                        <a href="<?= $store->getBaseUrl() ?>">
                                            <?= $store->getName() ?>
                                        </a>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        <?php endif ?>

                        <?php if ($cmsPageBlock->canShowCmsPages()): ?>
                            <h3><?= $cmsPageBlock->getTitle() ?></h3>
                            <ul>
                                <?php foreach ($cmsPageBlock->getCollection() as $page): ?>
                                    <li>
                                        <a href="<?= $page->getUrl() ?>">
                                            <?= $page->getTitle() ?>
                                        </a>
                                    </li>
                                <?php endforeach ?>
                                <?php foreach ($cmsPageBlock->getAdditionalCollection() as $link): ?>
                                    <li>
                                        <a href="<?= $link->getUrl() ?>">
                                            <?= $link->getTitle() ?>
                                        </a>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        <?php endif ?>
                    <?php endif ?>

                    <?php foreach ($block->getProviders() as $provider): ?>
                        <?php $items = $block->getProviderItems($provider) ?>
                        <?php if (count($items) > 0): ?>
                            <h3><?= $provider->getTitle() ?></h3>
                            <ul>
                                <?php foreach ($items as $item): ?>
                                    <li>
                                        <a href="<?= $item->getData('url') ?>"><?= $item->getData('title') ?></a>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                        <?php endif ?>
                    <?php endforeach ?>
                </td>
            </tr>
        </table>
    </div>
<?= $block->getChildHtml('map.pager') ?>