<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 07.11.18
 * Time: 8:12
 */

/** @var  $block \MageCloud\SalesOrder\Block\Adminhtml\Order\View\Attachments */
// @codingStandardsIgnoreFile

?>

<section class="admin__page-section edit-order-attachments">
    <ul class="note-list">
    </ul>
    <div class="edit-order-comments-block">
        <div class="edit-order-comments-block-title">
            <?= /* @escapeNotVerified */ __('Attachments for this Order') ?>
        </div>
    </div>
</section>