<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$product = $block->getProduct();
?>
<p>
	<?php 
		if($product->getArtworkGuidelines()!=""){
			//echo $product->getArtworkGuidelines();
			echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getArtworkGuidelines(), 'artwork_guidelines');
		}
		else
		{
			echo "N/A";
		}
	?> 
</p>