<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Aheadworks\Faq\Block\Article\Article $block */
?>
<div data-role="aw-faq-voting" data-bind="scope: 'awFaqVoting'" id="aw-faq__helpfulness">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=aw-faq-voting]": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
        }
    }
</script>