<?php
$category       = $this->getCurrentCategory();
$smallMobileBkp = $this->getSmallMobileBreakpoint();
$mobileBkp      = $this->getMobileBreakpoint();
$smallTabletBkp = $this->getSmallTabletBreakpoint();
$tabletBkp      = $this->getTabletBreakpoint();
$deskBkp        = $this->getDeskBreakpoint();
$largeDeskBkp   = $this->getLargeDeskBreakpoint();
?>
<style>
    <?php if($globalCss = $category->getCssGlobal()):?>
        <?php echo trim($globalCss); ?>
    <?php endif;?>
    
    <?php if($smallPhoneCss = $category->getCssPhoneSmall()):?>
        @media screen and (min-width: <?php echo $smallMobileBkp;?>) {<?php echo trim($smallPhoneCss);?>}
    <?php endif;?>

    <?php if($phoneCss = $category->getCssPhone()):?>
        @media (min-width: <?php echo $mobileBkp;?>) {<?php echo trim($phoneCss);?>}
    <?php endif;?>

    <?php if($smallTabletCss = $category->getCssTabletSmall()):?>
        @media (min-width: <?php echo $smallTabletBkp;?>) {<?php echo trim($smallTabletCss);?>}
    <?php endif;?>

    <?php if($tabletCss = $category->getCssTablet()):?>
        @media (min-width: <?php echo $tabletBkp;?>) {<?php echo trim($tabletCss);?>}
    <?php endif;?>

    <?php if($deskCss = $category->getCssDesktop()):?>
        @media (min-width: <?php echo $deskBkp;?>) {<?php echo trim($deskCss);?>}
    <?php endif;?>

    <?php if($largeDeskCss = $category->getCssDesktopLarge()):?>
        @media (min-width: <?php echo $largeDeskBkp;?>) {<?php echo trim($largeDeskCss);?>}
    <?php endif;?>
</style>
<?php if($js = $category->getCustomJs()):?>
    <script>
        <?php echo $js; ?>
    </script>
<?php endif;?>
