<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$portfolio = $this->getPortfolio();
//var_dump($this->getBaseImage($portfolio));exit;
?>
<!--  facebook open graph -->
<meta property="og:site_name" content="<?php /* @escapeNotVerified */ echo $storeManager->getStore()->getName(); ?>" />
<meta property="og:type" content="og:product" />
<meta property="og:title" content="<?php /* @escapeNotVerified */ echo strip_tags($portfolio->getName()); ?>" />
<meta property="og:image" content="<?php /* @escapeNotVerified */ echo strip_tags($this->getBaseImage($portfolio)); ?>" />
<meta property="og:description" content="<?php /* @escapeNotVerified */ echo $this->escapeQuote(strip_tags(nl2br($portfolio->getDescription()))); ?>" />
<meta property="og:url" content="<?php /* @escapeNotVerified */ echo strip_tags($this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true])); ?>" />
<!--  facebook open graph -->
