<?php
declare(strict_types=1);

/** @var \Mirasvit\Review\Block\Product\Review $block */

$review = $block->getReview();

if (!$review) {
    return '';
}
?>

<div class="review-title" itemprop="name">
    <?= $block->escapeHtml($review->getTitle()) ?>
    <?php if ($block->displayProductOption()):?>
        <div class="review-product-option">
            <?= /* @noEscape */ $block->getProductOptions($review); ?>
        </div>
    <?php endif;?>
</div>

<?php if (count($review->getRatingVotes())): ?>
    <div class="review-ratings">
        <?php foreach ($review->getRatingVotes() as $_vote): ?>
            <div class="rating-summary item"
                 itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                <span class="label rating-label">
                    <span><?= $block->escapeHtml($_vote->getRatingCode()) ?></span>
                </span>
                <div class="rating-result"
                     id="review_<?= /* @noEscape */
                     $review->getReviewId()
                     . '_vote_'
                     . $_vote->getVoteId() ?>"
                     title="<?= $block->escapeHtmlAttr($_vote->getPercent()) ?>%">
                    <meta itemprop="worstRating" content="1"/>
                    <meta itemprop="bestRating" content="100"/>
                    <span style="width: <?= $block->escapeHtmlAttr($_vote->getPercent()) ?>%">
                        <span itemprop="ratingValue">
                            <?= $block->escapeHtml($_vote->getPercent()) ?>%
                        </span>
                    </span>
                </div>
                <?= /* @noEscape */
                $secureRenderer->renderStyleAsTag(
                    'width:' . $_vote->getPercent() . '%',
                    'div#review_' . $review->getReviewId()
                    . '_vote_' . $_vote->getVoteId() . ' span'
                ) ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="review-content-container">
    <div class="review-content" itemprop="description">
        <?= /* @noEscape */ nl2br($block->escapeHtml($review->getDetail())) ?>
    </div>
    <?php
        echo $block->getChildBlock('proscons')
            ->setReview($review)
            ->toHtml();
        ?>
    <?php
        if ($block->isShowGallery()) {
            echo $block->getChildBlock('review.gallery')
                ->setReview($review)
                ->setProductId((int)$review->getProductId())
                ->toHtml();
        }
        ?>
    <div class="review-details">
        <p class="review-author">
            <span class="review-details-label">
                <?= $block->escapeHtml(__('Review by')) ?>
            </span>
            <strong class="review-details-value" itemprop="author">
                <?= $block->escapeHtml($review->getNickname()) ?>
            </strong>
            <?php if ($block->displayVerifiedBuyer() && $review->getIsVerifiedBuyer()): ?>
                <span style="color: #00b306">Verified Buyer</span>
            <?php endif; ?>
        </p>
        <p class="review-date">
            <span class="review-details-label">
                <?= $block->escapeHtml(__('Posted on')) ?>
            </span>
            <time class="review-details-value" itemprop="datePublished"
                  datetime="<?= $block->escapeHtmlAttr($block->getFormattedDate($review->getCreatedAt())) ?>">
                <?= $block->escapeHtml($block->getFormattedDate($review->getCreatedAt())) ?>
            </time>
        </p>
        <?php if ($block->getLocation($review)): ?>
            <div class="review-country">
                <strong>
                    <?= /* @noEscape */ $block->getLocation($review); ?>
                </strong>
                <?php if ($block->getCountryCode($review)): ?>
                    <div class="flag flag-<?= $block->escapeHtmlAttr($block->getCountryCode($review)) ?>"></div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
    <?php if ($commentBlock = $block->getChildBlock('review.comment')): ?>
        <?= $commentBlock->setEntityType('review')->setEntityId((int)$review->getId())->toHtml() ?>
    <?php endif; ?>
</div>


