<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Store\Block\Switcher $block */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManagerInterface = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currencyModel = $objectManager->create('Magento\Directory\Model\Currency');
$currencyInterface = $objectManager->get('Magento\Framework\Pricing\PriceCurrencyInterface');
$currencyCode = $storeManagerInterface->getStore()->getCurrentCurrencyCode();
$currencySymbol = $currencyModel->load($currencyCode)->getCurrencySymbol();
$websites = $storeManagerInterface->getWebsites();
$websiteid = $storeManagerInterface->getWebsite()->getWebsiteId();
?>

<div class="switcher store switcher-store" id="switcher-store">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Select Store')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <?php foreach ($websites as $website): ?>
            <?php if ($websiteid == $website->getId()): ?>
                <?php foreach ($block->getGroups() as $group): ?>
                    <?php if ($group->getId() == $block->getCurrentGroupId()): ?>
                        <div class="action toggle switcher-trigger"
                             role="button"
                             tabindex="0"
                             data-mage-init='{"dropdown":{}}'
                             data-toggle="dropdown"
                             data-trigger-keypress-button="true"
                             id="switcher-store-trigger">
                            <strong>
                                <span style="background-image:url('<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/flags/flag_' . $group->getCode() . '.png') ?>');background-position: center;width: 15px;height: 13px;display: inline-block;vertical-align: middle;"></span>
                                <span>(<?= $currencySymbol . " " . $currencyCode?>)</span>
                            </strong>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <ul class="dropdown switcher-dropdown" data-target="dropdown">
            <?php foreach ($websites as $website): ?>
                <?php if (!($websiteid == $website->getId())): ?>
                    <li class="switcher-option">
                        <a href="<?php echo $website->getDefaultStore()->getCurrentUrl() ?>">
                            <span style="background-image:url('<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/flags/flag_' . $website->getCode() . '.png') ?>');background-position: center;width: 15px;height: 13px;display: inline-block;vertical-align: bottom;"></span>
                            <span style="text-transform: uppercase;">(<?= $currencyInterface->getCurrencySymbol($website->getCode()) . ' ' . $website->getCode()?>)</span>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
